FROM stifstof/jnlp-slave-arm:latest

USER root

RUN apt-get update \
  && apt-get -y --no-install-recommends install docker \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#RUN curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

#RUN chmod +x /usr/local/bin/docker-compose

#RUN ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

#RUN ls -lah /usr/bin/
RUN apt-get update
RUN apt-get install -y libffi-dev libssl-dev
RUN apt-get install -y python3 python3-pip
RUN apt-get remove python-configparser
RUN apt-get install docker-compose -y
RUN export PATH="$PATH:/usr/bin/docker-compose:/usr/local/bin/docker-compose"
RUN docker-compose --version
